# Generated by Django 4.1.2 on 2023-09-30 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_network', '0006_user_profile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True),
        ),
    ]
